PROTO_DIR=protobuf
OUT_DIR=./generated/tasks

all: run lint test

test:
	-cd api_service && go test -v ./...
	-cd db_service && go test -v ./...

run:
	docker-compose up -d 

lint:
	-cd api_service && golangci-lint run ./...
	-cd db_service && golangci-lint run ./...
	-cd kafka_service && golangci-lint run ./...
